import { Schedule } from 'src/interfaces/Schedules';
import { Serie } from 'src/interfaces/Series';

export const SEASON_SCHEDULE: Schedule[] = [
  {
    id: 1,
    PlayingDate: new Date(2015, 8, 23),
    Fighter1: 'Heihachi Mishima',
    Fighter2: 'Paul Phoenix',
    Fighter1Score: 4,
    Fighter2Score: 3,
    Stage: 'Beach Island',
  },
  {
    id: 2,
    PlayingDate: new Date(2015, 8, 26),
    Fighter1: 'Anna Williams',
    Fighter2: 'Lei Wulong',
    Fighter1Score: 7,
    Fighter2Score: 2,
    Stage: 'Carnival',
  },
  {
    id: 3,
    PlayingDate: new Date(2015, 8, 28),
    Fighter1: 'Nina Williams',
    Fighter2: 'Yoshimitsu',
    Fighter1Score: 4,
    Fighter2Score: 6,
    Stage: 'Forest',
  },
  {
    id: 4,
    PlayingDate: new Date(2015, 9, 1),
    Fighter1: 'Bryan Fury',
    Fighter2: 'Eddy Gordo',
    Fighter1Score: 8,
    Fighter2Score: 2,
    Stage: 'High School',
  },
  {
    id: 5,
    PlayingDate: new Date(2015, 9, 82),
    Fighter1: 'Hwoarang',
    Fighter2: 'Jin Kazama',
    Fighter1Score: 3,
    Fighter2Score: 6,
    Stage: 'Hong Kong Street',
  },
  {
    id: 6,
    PlayingDate: new Date(2015, 9, 12),
    Fighter1: 'Julia Chang',
    Fighter2: 'King',
    Fighter1Score: 2,
    Fighter2Score: 6,
    Stage: 'Junky Mansion',
  },
  {
    id: 7,
    PlayingDate: new Date(2015, 9, 1),
    Fighter1: 'Forest Law',
    Fighter2: 'Mokujin',
    Fighter1Score: 8,
    Fighter2Score: 7,
    Stage: 'Laboratoary Courtyard',
  },
  {
    id: 8,
    PlayingDate: new Date(2015, 9, 82),
    Fighter1: 'Ling Xiaoyu',
    Fighter2: 'Kazuya Mishima',
    Fighter1Score: 4,
    Fighter2Score: 4,
    Stage: 'Martial Arts Dojo',
  },
  {
    id: 9,
    PlayingDate: new Date(2015, 9, 12),
    Fighter1: 'Tiger Jackson',
    Fighter2: 'Panda',
    Fighter1Score: 5,
    Fighter2Score: 1,
    Stage: 'Mexican Temple',
  },
];

export const SERIES: Serie[] = [
  { id: 1, name: 'Tekken 2' },
  { id: 2, name: 'Tekken 3' },
  { id: 3, name: 'Tekken 4' },
  { id: 4, name: 'Tekken 5' },
  { id: 5, name: 'Dark Resurrection' },
  { id: 6, name: 'Tekken 6' },
  { id: 7, name: 'Bloodline Rebellion' },
  { id: 8, name: 'Tekken 7' },
  { id: 9, name: 'TFated Retribution' },
];
